### ISSUE TITLE
Lab 3 problema generare schelet memory-corruption

### ISSUE THREAD

**Issue by Censebastian** [cs-pub-ro/operating-systems#109]
Am incercat sa generez scheletele si mi-a dat eroarea:
![image](https://github.com/user-attachments/assets/d2f1a887-2aaf-4edf-b44b-2448df9c02df)

**Comment by Alex-deVis** [comment]
I am unable to reproduce this locally, but it seems to be a valid problem since the branch for `.d` files (`elif re.match(r".*\.d$", src):`) does not define: `remove` and `end_string`.
